### ISSUE TITLE
请问编译失败的时候，在哪里能看到报错信息？

### ISSUE THREAD

**Issue by rekcah1986** [mullezki/generator-layaair#1]
npm-debug.log里也看了，没有有用的信息

**Comment by mullezki** [comment]
Sorry，最近比较忙没来看。。之前的调用编译进程出错的话会直接抛异常。现在修改了调用子进程的方式，会在控制台上显示编译错误信息，并添加了编译错误日志，在项目目录的build.log里。

**Comment by mullezki** [comment]
直接在npm里更新generator-layaair就行了

**Comment by rekcah1986** [comment]
收到，鼓掌~
